markdown: rdiscount
permalink: /:title/
url: http://www.nbyteam.com
name: 明月夜 小轩窗
author: NByteam.com
qq:
email: pomfei@nbyteam.com
duoshuo: nbyteam
beian:
cnzz:
weibo: 1830766915
github: pomfei
highlighter: true
safe: true
paginate: 20
about: "性别男，爱好女"

timezone: Asia/Shanghai